{
  "formatVersion": "1.1",
  "component": {
    "url": "../../shared/1.0.0.1-rc-015/shared-1.0.0.1-rc-015.module",
    "group": "com.github.Imajy.eazyCmp",
    "module": "shared",
    "version": "1.0.0.1-rc-015",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.11.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose-viewmodel",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.github.alexzhirkevich",
          "module": "compottie",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0-beta05"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared-iosArm64Main-1.0.0.1-rc-015.klib",
          "url": "shared-iosarm64-1.0.0.1-rc-015.klib",
          "size": 1155728,
          "sha512": "b5b3b043138ba6f4e496753c15fe8c0668c23be1cfbe9de796fd990981ae58389a9ddca4f732dd2ba7cc32afc3d823658517fde0bc5a6ae4a419853d46706041",
          "sha256": "e93611037f5b0cc2e47fe62fef48d8583da2574239791d076ab025b5fa2671ca",
          "sha1": "00c791cbaf8c5d6b51b6388cf796888a6da72adc",
          "md5": "cd070a1ca47a001029f4a3fd226f843b"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "shared-iosarm64-1.0.0.1-rc-015-sources.jar",
          "url": "shared-iosarm64-1.0.0.1-rc-015-sources.jar",
          "size": 168830,
          "sha512": "7627755dd9eb1f9ec74a2cdb5e65133428b3dfdf63796637e8a0f23745b418c0dc643dee7322ff12dc3b176afa24c286aa2d245e61230f406669a014bb0a03d3",
          "sha256": "f97aa84586f3edf06fb0d73d36d883d81f6ff95e93c31a945c19e9219b5bcbc4",
          "sha1": "7bbadf65b8f4b2fefe5e8c7b87c897060c3025ce",
          "md5": "2b7329df600f77b1b982616662927805"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.11.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose-viewmodel",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.github.alexzhirkevich",
          "module": "compottie",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0-beta05"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared-1.0.0.1-rc-015.kotlin_resources.zip",
          "url": "shared-iosarm64-1.0.0.1-rc-015-kotlin_resources.kotlin_resources.zip",
          "size": 3175,
          "sha512": "2020a2a6053435e51370b62f91f5be458aaba074f73bd7462fdc36bd0a5e5e2e47abcf41282e037cbae0a4af8f24d2694dfd57ac6242b898e53b37e8f7f668d4",
          "sha256": "afb88401f1541a9ada0823a73ef21bc4b69353bd3ad27a84d8234420e061125f",
          "sha1": "dfdcfa397f9c1416a8aad8e779f7ecc6c7eecf97",
          "md5": "d5692504c309e0f541fecfe91e684ed2"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.11.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose-viewmodel",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.github.alexzhirkevich",
          "module": "compottie",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0-beta05"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared-iosarm64-1.0.0.1-rc-015-metadata.jar",
          "url": "shared-iosarm64-1.0.0.1-rc-015-metadata.jar",
          "size": 22614,
          "sha512": "457c9b502f1bb016fbf0f4d83a76678ad1f4fe6a9a1d7456a2061b0b339c61b5fd8eb58bf8ec1bc0139c38ebe3212b5062c906a09d46e2634da4f20d203b079d",
          "sha256": "cb7557c5efc2237ff5ef20ab50e8c7c7981580544e98c77f044de2a8e4e16cc2",
          "sha1": "00ad09cd801cbe4139439f33325053027eb010cc",
          "md5": "ed687efb5fa89319f3884c8c13b38cd5"
        }
      ]
    }
  ]
}
