{
  "formatVersion": "1.1",
  "component": {
    "url": "../../shared/1.0.0.1-rc-032/shared-1.0.0.1-rc-032.module",
    "group": "com.github.Imajy.eazyCmp",
    "module": "shared",
    "version": "1.0.0.1-rc-032",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.11.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose-viewmodel",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.github.alexzhirkevich",
          "module": "compottie",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0-beta05"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared-iosArm64Main-1.0.0.1-rc-032.klib",
          "url": "shared-iosarm64-1.0.0.1-rc-032.klib",
          "size": 1231852,
          "sha512": "12aae1993fed340b1a36b975c8745dad960cbdcf6cc8211b0c1993e4dbaf152eecdb67f657fa3a52505cdf3277be989ef1ab3f98541acdf69e5a56d2b46e05c9",
          "sha256": "e8615998ceead3b8cedf5fe2ee8266b9c4730615e6888431c3cb8408e3c50ba7",
          "sha1": "77824b8e32785b19178f5256e227150f7dae8f48",
          "md5": "9e93d4732922d1718eaa4ca697e36a1b"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "shared-iosarm64-1.0.0.1-rc-032-sources.jar",
          "url": "shared-iosarm64-1.0.0.1-rc-032-sources.jar",
          "size": 178892,
          "sha512": "2049b0c7511cc1bf7d07bc42268bc2545dcb555bedf89269b7a9cb37f6d074fbe9010159519b6590b90542b131acc682b79296a29b313d049011eb7ca99b47f3",
          "sha256": "603c5615e67613f3eed8241fa2d948c8b3b78385052f37989602d142bb7c3bcb",
          "sha1": "5d8b4ccaff5bffb527700ae06226ae1e7e5a803d",
          "md5": "63a7961e584d50842b07136b2e245d92"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.11.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose-viewmodel",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.github.alexzhirkevich",
          "module": "compottie",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0-beta05"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared-1.0.0.1-rc-032.kotlin_resources.zip",
          "url": "shared-iosarm64-1.0.0.1-rc-032-kotlin_resources.kotlin_resources.zip",
          "size": 3175,
          "sha512": "2020a2a6053435e51370b62f91f5be458aaba074f73bd7462fdc36bd0a5e5e2e47abcf41282e037cbae0a4af8f24d2694dfd57ac6242b898e53b37e8f7f668d4",
          "sha256": "afb88401f1541a9ada0823a73ef21bc4b69353bd3ad27a84d8234420e061125f",
          "sha1": "dfdcfa397f9c1416a8aad8e779f7ecc6c7eecf97",
          "md5": "d5692504c309e0f541fecfe91e684ed2"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.11.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose-viewmodel",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.github.alexzhirkevich",
          "module": "compottie",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0-beta05"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared-iosarm64-1.0.0.1-rc-032-metadata.jar",
          "url": "shared-iosarm64-1.0.0.1-rc-032-metadata.jar",
          "size": 23388,
          "sha512": "c700fb332ed89d4e54d57cf050be2d97509abda384abf6ead7d102de2931a558af99964a823748d54ade34e90c63d210baa67097a9237589581421f57870cd4f",
          "sha256": "6793b2fad8e6aa68b6aac6156d06818abef9982dd3af7c9849540bb9d2e32bc3",
          "sha1": "205ba47268c49337fba7bb335a311db0a2c9e110",
          "md5": "da8b03277ebcece43e82e65ae3563a52"
        }
      ]
    }
  ]
}
