{
  "formatVersion": "1.1",
  "component": {
    "url": "../../shared/1.0.0.1-rc-040/shared-1.0.0.1-rc-040.module",
    "group": "com.github.Imajy.eazyCmp",
    "module": "shared",
    "version": "1.0.0.1-rc-040",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.11.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose-viewmodel",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.github.alexzhirkevich",
          "module": "compottie",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0-beta05"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared-iosSimulatorArm64Main-1.0.0.1-rc-040.klib",
          "url": "shared-iossimulatorarm64-1.0.0.1-rc-040.klib",
          "size": 1284449,
          "sha512": "1f662faac8d4157647e18a08c3eca7639060a6554f491284bbf73a996772f3e9f27d508e2e2fdfdd7dab500fdf8d504b89326d0992d500ef47e02743dac3ef01",
          "sha256": "dcdf2e87637675234818380bbd67492c1d80d4b31048e2277464d52328f435fd",
          "sha1": "a575e7245c14be4d3559d64fbfa5c71b63c12f8f",
          "md5": "6a5528752acc6b34a71a2189005fa714"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "shared-iossimulatorarm64-1.0.0.1-rc-040-sources.jar",
          "url": "shared-iossimulatorarm64-1.0.0.1-rc-040-sources.jar",
          "size": 185792,
          "sha512": "d20eb78d7baac7994e4d3cf3eb4636652756be2d9f8c030121e609f2bf7318af37430b004aaefbd1af674067dd50ac12809a8820d06498da59652add71381dfd",
          "sha256": "c37437d3ca3caf6f16767a0532f80865a81973b02f6929b2b4bb307297f1aa1c",
          "sha1": "a5a7de29d3b67b189e57113c93b1c3cbb66a57b4",
          "md5": "47825146374c6783772789c171e9f944"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.11.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose-viewmodel",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.github.alexzhirkevich",
          "module": "compottie",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0-beta05"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared-1.0.0.1-rc-040.kotlin_resources.zip",
          "url": "shared-iossimulatorarm64-1.0.0.1-rc-040-kotlin_resources.kotlin_resources.zip",
          "size": 3175,
          "sha512": "2020a2a6053435e51370b62f91f5be458aaba074f73bd7462fdc36bd0a5e5e2e47abcf41282e037cbae0a4af8f24d2694dfd57ac6242b898e53b37e8f7f668d4",
          "sha256": "afb88401f1541a9ada0823a73ef21bc4b69353bd3ad27a84d8234420e061125f",
          "sha1": "dfdcfa397f9c1416a8aad8e779f7ecc6c7eecf97",
          "md5": "d5692504c309e0f541fecfe91e684ed2"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.11.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose-viewmodel",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.github.alexzhirkevich",
          "module": "compottie",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0-beta05"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared-iossimulatorarm64-1.0.0.1-rc-040-metadata.jar",
          "url": "shared-iossimulatorarm64-1.0.0.1-rc-040-metadata.jar",
          "size": 23388,
          "sha512": "c700fb332ed89d4e54d57cf050be2d97509abda384abf6ead7d102de2931a558af99964a823748d54ade34e90c63d210baa67097a9237589581421f57870cd4f",
          "sha256": "6793b2fad8e6aa68b6aac6156d06818abef9982dd3af7c9849540bb9d2e32bc3",
          "sha1": "205ba47268c49337fba7bb335a311db0a2c9e110",
          "md5": "da8b03277ebcece43e82e65ae3563a52"
        }
      ]
    }
  ]
}
