{
  "formatVersion": "1.1",
  "component": {
    "url": "../../shared/1.0.0.1-rc-005/shared-1.0.0.1-rc-005.module",
    "group": "com.github.Imajy.eazyCmp",
    "module": "shared",
    "version": "1.0.0.1-rc-005",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.11.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose-viewmodel",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.github.alexzhirkevich",
          "module": "compottie",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0-beta05"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared-iosArm64Main-1.0.0.1-rc-005.klib",
          "url": "shared-iosarm64-1.0.0.1-rc-005.klib",
          "size": 1140688,
          "sha512": "418aaddfc63cff4c83031b1ba881ab17cc26c229a801108b91981b7cbdf9e9bed42b20a9fd3e51404e3aaa5fabacd82634e9e3c09fa8aad22139df611b2f0d09",
          "sha256": "e94d32c1a3945b9f04412e062f3f9d47a5b4b766bfbdcc9fa176ae333f30ed72",
          "sha1": "a13411a3877f8fbb409750d5f3800ccd572cc8c9",
          "md5": "d9bf6a6807016721a1611625763edf5a"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "shared-iosarm64-1.0.0.1-rc-005-sources.jar",
          "url": "shared-iosarm64-1.0.0.1-rc-005-sources.jar",
          "size": 167127,
          "sha512": "261a62bc7ed284f716f6f4cbad3fa2ae884faf4f0cbeb7bf3822dac00a865256dabb35fa3155f156314ccc04a47f1035e61a175b7399be49697d61acbfd86553",
          "sha256": "8fe23c7eabbee5d0b4ea400f69872ee3ea4b8b0bd12af5f598c1a7cfa93c8053",
          "sha1": "e1a2b9fbded95eb098708075950abfa0e2e97085",
          "md5": "ead6f2265bac633d67d85d0fab97b4c4"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.11.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose-viewmodel",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.github.alexzhirkevich",
          "module": "compottie",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0-beta05"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared-1.0.0.1-rc-005.kotlin_resources.zip",
          "url": "shared-iosarm64-1.0.0.1-rc-005-kotlin_resources.kotlin_resources.zip",
          "size": 3175,
          "sha512": "2020a2a6053435e51370b62f91f5be458aaba074f73bd7462fdc36bd0a5e5e2e47abcf41282e037cbae0a4af8f24d2694dfd57ac6242b898e53b37e8f7f668d4",
          "sha256": "afb88401f1541a9ada0823a73ef21bc4b69353bd3ad27a84d8234420e061125f",
          "sha1": "dfdcfa397f9c1416a8aad8e779f7ecc6c7eecf97",
          "md5": "d5692504c309e0f541fecfe91e684ed2"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.11.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose-viewmodel",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.github.alexzhirkevich",
          "module": "compottie",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0-beta05"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared-iosarm64-1.0.0.1-rc-005-metadata.jar",
          "url": "shared-iosarm64-1.0.0.1-rc-005-metadata.jar",
          "size": 22614,
          "sha512": "457c9b502f1bb016fbf0f4d83a76678ad1f4fe6a9a1d7456a2061b0b339c61b5fd8eb58bf8ec1bc0139c38ebe3212b5062c906a09d46e2634da4f20d203b079d",
          "sha256": "cb7557c5efc2237ff5ef20ab50e8c7c7981580544e98c77f044de2a8e4e16cc2",
          "sha1": "00ad09cd801cbe4139439f33325053027eb010cc",
          "md5": "ed687efb5fa89319f3884c8c13b38cd5"
        }
      ]
    }
  ]
}
