{
  "formatVersion": "1.1",
  "component": {
    "url": "../../web/1.0.0.1-rc-059/web-1.0.0.1-rc-059.module",
    "group": "com.github.Imajy.eazyCmp",
    "module": "web",
    "version": "1.0.0.1-rc-059",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.11.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "web-js-1.0.0.1-rc-059.klib",
          "url": "web-js-1.0.0.1-rc-059.klib",
          "size": 3495679,
          "sha512": "78910578f232422898275bf585afc5046b580902fd27507aa70361d86e820dfe22c38914549a1bdb612c01e3b8a22d995207c8ae366f97848bbbf8f648c4ee56",
          "sha256": "08af09d9d38bdd780a17cfdda8e3fde698747acbc4b272ed4ecdae9f91cc55d5",
          "sha1": "043627e69145f725a0e356f2d63e442c6148f540",
          "md5": "4e931426703572e8eee3219464751280"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.11.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "web-js-1.0.0.1-rc-059.klib",
          "url": "web-js-1.0.0.1-rc-059.klib",
          "size": 3495679,
          "sha512": "78910578f232422898275bf585afc5046b580902fd27507aa70361d86e820dfe22c38914549a1bdb612c01e3b8a22d995207c8ae366f97848bbbf8f648c4ee56",
          "sha256": "08af09d9d38bdd780a17cfdda8e3fde698747acbc4b272ed4ecdae9f91cc55d5",
          "sha1": "043627e69145f725a0e356f2d63e442c6148f540",
          "md5": "4e931426703572e8eee3219464751280"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "web-js-1.0.0.1-rc-059-sources.jar",
          "url": "web-js-1.0.0.1-rc-059-sources.jar",
          "size": 9035,
          "sha512": "4685bd9f7f3c5a361c24494b36ec5a0db64cf1f4339159aaba42378dd61808e2dd4d1a1a0c8c3633e04bc695e06c331b6962a55bc1fa01225b2fc2bcb8516e71",
          "sha256": "b46e06f6732440591bedd7a3a5a76b24f8135eb88e09f260b5103cebdd7a98bb",
          "sha1": "680fc3fa3d2282e2917add3c964c129d2c7a7967",
          "md5": "8644f0b5d1985a81584539e6d97a6ea3"
        }
      ]
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.11.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "web-1.0.0.1-rc-059.kotlin_resources.zip",
          "url": "web-js-1.0.0.1-rc-059-kotlin_resources.kotlin_resources.zip",
          "size": 344,
          "sha512": "09bb87f6fe4283c4ae13236d7afd8c23724362ddc498c223947bca5e6181deb272789ceb238be910ed2e74abb0941a1c4e1f71d9943fb99f9e613c94ada1c008",
          "sha256": "938a2f4e8cce66156ba1954f72485d6e48cb27e8ded45592708d457e252de887",
          "sha1": "313b13abd9233139f99956499034121362d70b81",
          "md5": "9f85f3e4e908db45d921acd0f41c3344"
        }
      ]
    }
  ]
}
